### ISSUE TITLE
wrong download link

### ISSUE THREAD

**Issue by lidewu** [extremenetworks/Virtual_EXOS#10]
exosvm.gns3a
At 36  has wrong download link:
"direct_download_url": "https://akamai-ep.extremenetworks.com/Extreme_P/github-en/Virtual_EXOS/EXOS-VM_v22.5.1.7.qcow2"

==>

"direct_download_url": "https://akamai-ep.extremenetworks.com/Extreme_P/github-en/Virtual_EXOS/EXOS-VM_v22.6.1.4.qcow2"

**Comment by stewilliams-extr** [comment]
Updated
