### ISSUE TITLE
unable to create exos instance after successfully importing the appliance

### ISSUE THREAD

**Issue by Sheshagiri** [extremenetworks/Virtual_EXOS#11]
I'm able to import the appliance successfully and exos appears in the list of installed appliances under switches but when I drag that to the workspace I see the following error.

"Error while creating node: The image vm-22.1.1.5.iso is missing"

When I explicitly select the iso (right click the appliance -->  Configure Template --> CD/DVD) to the downloaded file the issue disappears.
![image](https://user-images.githubusercontent.com/2954796/47408483-397a4b80-d77d-11e8-8df6-999ed2c8b9f4.png)

**Comment by stewilliams-extr** [comment]
Did you follow this guide?  https://github.com/extremenetworks/Virtual_EXOS/blob/master/GNS3_EXOS-VM_Guide.md

**Comment by Sheshagiri** [comment]
@stewilliams-extr yes.

**Comment by stewilliams-extr** [comment]
Then you import the appliance with the exosvm.gns3a it will walk you through downloading the qcow2 and using it as your drive.  You don't need to use the .iso when using GNS3.
