### ISSUE TITLE
OSPFv3 - routes are showing as /128

### ISSUE THREAD

**Issue by msivanich** [extremenetworks/Virtual_EXOS#13]
OSPFv3 routes being shared are being shared with a prefix of /128 rather than the prefix that is defined.  Example two Virtual_EXOS VM's, switch 1 has a vlan that is passively set in OSPFv3 with a prefix of fd3c:3c98:eacc:d00::/64.  Switch 2 receives the route but shows up as fd3c:3c98:eacc:d00::/128 rather than /64.

Environment:
VMware ESX 6.5.0 (Build 4887370) 
EXOS VM Image 16.2.1.6
VMs hooked up to same virtual switch

**Comment by stewilliams-extr** [comment]
Please test with the latest version of EXOS-VM and re-create issue if it's still present.  Sorry we didn't respond.  You can also submit your questions to our community at https://community.extremenetworks.com/.
