### ISSUE TITLE
Eve-ng, can`t ping in vlan

### ISSUE THREAD

**Issue by freedomwarrior** [extremenetworks/Virtual_EXOS#14]
Hello.
I`m using eve-ng for exos and I trying to connect exos<--->Cisco 7206 to test some features.
When I connect them with default vlan, I got l3 connect(ping works), but when I add some vlans and assign IPs, I have no ping between them.

**Comment by craymond422** [comment]
Can ping all interfaces and nodes between distribution & access layer. 
Core can ping 10.145.255.1 & 10.145.255.3 but not 10.145.255.2
10.145.2551 - svi interface gateway
10.145.255.2 - mgmt ip on access layer switch. native vlan. trunked on uplink
10.145.255.3 - pc on an access port on access layer switch

Distribution Switch - configured L2 & L3 interfaces on this device: 
vlan 255 name v255-10.145.1.0/24
int vlan 255 
10.145.255.1 255.255.255.0
!
interface GigabitEthernet0/1
 switchport trunk allowed vlan 100,255,500
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 255
 switchport mode trunk
 media-type rj45
 negotiation auto
end
B1D700-MDFA#ping 10.145.255.1 --------------------------------------------------int vlan 255
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.145.255.1, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 1/2/8 ms
B1D700-MDFA#ping 10.145.255.2--------------------------------------------------switch mgmt IP address. native vlan 
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.145.255.2, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 4/6/8 ms
B1D700-MDFA#ping 10.145.255.3 -------------------------------------------------PC on an access port on switch
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.145.255.3, timeout is 2 seconds: 
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 1/4/7 ms
B1D700-MDFA#

________________________________________
Access Switch
!
interface GigabitEthernet0/1
 switchport trunk allowed vlan 100,255,500
 switchport trunk encapsulation dot1q
 switchport trunk native vlan 255
 switchport mode trunk
 media-type rj45
 negotiation auto
end
!
interface Vlan255
 ip address 10.145.255.2 255.255.255.0
end
ip default-gateway 10.145.255.1
B1D700-UDFA#ping 10.145.255.1
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.145.255.1, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 4/5/8 ms
B1D700-UDFA#ping 10.145.255.2
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.145.255.2, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 1/1/1 ms
B1D700-UDFA#ping 10.145.255.3
Type escape sequence to abort.
Sending 5, 100-byte ICMP Echos to 10.145.255.3, timeout is 2 seconds:
!!!!!
Success rate is 100 percent (5/5), round-trip min/avg/max = 1/2/5 ms
B1D700-UDFA#
