### ISSUE TITLE
 unable to save configuration on EXOS Appliance GNS3 2.2.5

### ISSUE THREAD

**Issue by erosxy** [extremenetworks/Virtual_EXOS#17]
I setup a new EXOS Appliance (exosvm.30.2) and when I start it out, whenever I made changes, and wanted to save configuration with usual save configuration cmd, it is cancelled automatically ,whatever I put yes/no !!!
############################
* EXOS-VM.2 # save
No default configuration database has been selected to boot up the system.
Save configuration will set the new configuration as the default database.

Do you want to save configuration to primary.cfg? (y/N)
Save configuration cancelled.
##########################

it is a very annoying Issue ! is there someone who is runing into the same issue ? Did I missed some options ?

**Comment by stewilliams-extr** [comment]
I tested it on EXOS 30.2 and 30.5 and both work fine on GNS3 2.2.5.  I'm using GNS3-VM running as Main Server mode.

Are you using the quemu images?

EXOS-VM.3 # show version | in Switch
Switch      : PN:1N2039    SN:123456   Rev 01 BootROM: 1.2        IMG: 30.2.1.8
EXOS-VM.4 # save
The configuration file primary.cfg already exists.
Do you want to save configuration to primary.cfg and overwrite it? (y/N) Yes
Saving configuration primary.cfg  on master ........ done!
Configuration saved to primary.cfg successfully.
EXOS-VM.5 #

**Comment by erosxy** [comment]
Hi and thank very much for taking charge of my request.

 

I’ve the same setting so I have  had to ininstall gns3 and reinstall it and now, i can perform save cmd without error but another issue came up

I can no loguer see the device that I drag and drop on the project window… any idea please ?

 

Thank you

               

 

De : stewilliams-extr <notifications@github.com> 
Envoyé : mercredi 18 mars 2020 15:57
À : extremenetworks/Virtual_EXOS <Virtual_EXOS@noreply.github.com>
Cc : yansof <expertsof8@gmail.com>; Author <author@noreply.github.com>
Objet : Re: [extremenetworks/Virtual_EXOS] unable to save configuration on EXOS Appliance GNS3 2.2.5 (#17)

 

I tested it on EXOS 30.2 and 30.5 and both work fine on GNS3 2.2.5. I'm using GNS3-VM running as Main Server mode.

Are you using the quemu images?

EXOS-VM.3 # show version | in Switch
Switch : PN:1N2039 SN:123456 Rev 01 BootROM: 1.2 IMG: 30.2.1.8
EXOS-VM.4 # save
The configuration file primary.cfg already exists.
Do you want to save configuration to primary.cfg and overwrite it? (y/N) Yes
Saving configuration primary.cfg on master ........ done!
Configuration saved to primary.cfg successfully.
EXOS-VM.5 #

**Comment by erosxy** [comment]
Okey I found out why the save cmd didn’t work before :  the save cmd doesn’t pass only when I’m logged with Mobaxterm via Telnet

It works fine with default Putty so it’s very strange behavior

 

 

 

De : expertsof8@gmail.com <expertsof8@gmail.com> 
Envoyé : mercredi 18 mars 2020 17:24
À : 'extremenetworks/Virtual_EXOS' <reply@reply.github.com>; 'extremenetworks/Virtual_EXOS' <Virtual_EXOS@noreply.github.com>
Cc : 'Author' <author@noreply.github.com>
Objet : RE: [extremenetworks/Virtual_EXOS] unable to save configuration on EXOS Appliance GNS3 2.2.5 (#17)

 

Hi and thank very much for taking charge of my request.

 

I’ve the same setting so I have  had to ininstall gns3 and reinstall it and now, i can perform save cmd without error but another issue came up

I can no loguer see the device that I drag and drop on the project window… any idea please ?

 

Thank you

               

 

De : stewilliams-extr <notifications@github.com <mailto:notifications@github.com> > 
Envoyé : mercredi 18 mars 2020 15:57
À : extremenetworks/Virtual_EXOS <Virtual_EXOS@noreply.github.com <mailto:Virtual_EXOS@noreply.github.com> >
Cc : yansof <expertsof8@gmail.com <mailto:expertsof8@gmail.com> >; Author <author@noreply.github.com <mailto:author@noreply.github.com> >
Objet : Re: [extremenetworks/Virtual_EXOS] unable to save configuration on EXOS Appliance GNS3 2.2.5 (#17)

 

I tested it on EXOS 30.2 and 30.5 and both work fine on GNS3 2.2.5. I'm using GNS3-VM running as Main Server mode.

Are you using the quemu images?

EXOS-VM.3 # show version | in Switch
Switch : PN:1N2039 SN:123456 Rev 01 BootROM: 1.2 IMG: 30.2.1.8
EXOS-VM.4 # save
The configuration file primary.cfg already exists.
Do you want to save configuration to primary.cfg and overwrite it? (y/N) Yes
Saving configuration primary.cfg on master ........ done!
Configuration saved to primary.cfg successfully.
EXOS-VM.5 #
