### ISSUE TITLE
VXLAN issues

### ISSUE THREAD

**Issue by michaelpsomiadis** [extremenetworks/Virtual_EXOS#18]
Hello,

I'm attempting to lab out with VXLAN in virtual EXOS but i'm running into an issue where no L2 is being sent across (ARP and DHCP discover as its easy to do with vPC). I note that someone has posted on the community with seemingly the same issue as me, I pretty much have the same setup in GNS3.

https://community.extremenetworks.com/extremeswitching-exos-223284/gns3-vxlan-7828447

I don't have a set of real hardware that isn't in production to play with, so it would be nice if I could do this in GNS3.

I can see the UDP packets making it across the link between the two switches, however it appears it isn't processed by the destination VTEP and put back on the physical VLAN on the other end. Wondering if someone can replicate? I am using an olderish version (30.4.1.2) but considering that post was only made a month ago with no responses I assume its still an issue.

**Comment by stewilliams-extr** [comment]
VXLAN is not fully supported in EXOS VM.  We do have feature requests submitted to add support for it in the future.
