### ISSUE TITLE
Security Vulnerability - EXOS Software SSRF

### ISSUE THREAD

**Issue by paragonsec** [extremenetworks/Virtual_EXOS#19]
There is a SSRF vulnerability in the MLAG login API. This allows a user to scan other devices through the EXOS device to see what other ports are open, or scan the device itself from localhost.

Proof Image:
![image](https://user-images.githubusercontent.com/28866353/94016362-a0427e00-fd73-11ea-9cfb-c3f7ff9f7e4a.png)

Vulnerable Code:
The first code shows the peer1_ip and peer2_ip is being set:

![image](https://user-images.githubusercontent.com/28866353/94016562-de3fa200-fd73-11ea-8500-bbf69f12f60f.png)

Then it is called by a Python request.post call which does not sanitize anything after the `http://` prepended protocol allowing the user to insert data like `127.0.0.1:22`.

![image](https://user-images.githubusercontent.com/28866353/94016710-15ae4e80-fd74-11ea-8046-9e8b2e67c0cf.png)

This vulnerability is low since you can't bypass the prepended http protocol but to fix you should sanitize the peer1_ip and peer2_ip to be only in the IP format or if also allowing hostname strip anything that isn't a letter or number.

**Comment by stewilliams-extr** [comment]
Our security team did received your report.  I have asked them to respond to you via email if there are any additional questions.
