### ISSUE TITLE
About GNS3 import / Export

### ISSUE THREAD

**Issue by noplay** [extremenetworks/Virtual_EXOS#2]
Hi,

Member of GNS3 team here. I have a good news for you in the 1.5 of GNS3 we have include a system for exporting and importing project as a single file (behind the scene it's just a zip).

You can  test it via the File menu => Export portable project

Let us know if it's work for you and if you need improvement.

**Comment by stewilliams-extr** [comment]
Thanks for the heads up.  We have been looking for a feature like this.  I see one problem with it.  When you click "Export portable project" and select No to include base image.  It's included anyway.  I will hop over to GNS3 and submit the bug.

**Comment by stewilliams-extr** [comment]
When GNS3 bug is fixed we will update the guides to reflect the new process. 

https://github.com/GNS3/gns3-gui/issues/1409#issuecomment-235698460

**Comment by noplay** [comment]
1.5.2 of GNS3 has been released with fix for import of. Thanks for your
support

**Comment by stewilliams-extr** [comment]
Readme updated to reflect the new version.
