### ISSUE TITLE
Images < EXOS VM 21

### ISSUE THREAD

**Issue by laxxie** [extremenetworks/Virtual_EXOS#21]
Hi Guys,
we are using a X670 with version 16.2. Do you have also VMs for GNS3 for such version which are < 21 ?
Or does have one of these VMs have the same featureset etc. which can be used to simulate our current device?

Regards

**Comment by ZdenekPala** [comment]
We do have VMware based switch. Not sure if it helps.

**Comment by stewilliams-extr** [comment]
Iaxxie,

We do have un-published VM versions of 16.2.  I would recommend using the newer ones as they are more stable.
