### ISSUE TITLE
EXOS vm 31.1.1.3 ESXi 7

### ISSUE THREAD

**Issue by gauthierpjn** [extremenetworks/Virtual_EXOS#22]
Hi, 

I'm trying to install the EXOS vm 31.1.1.4 on my ESXi 7.0.0 and I always end-up with the following error: "The i386 vm virtual disk needs to be sized at least 4GB large."

My HD is configured for 8GB so, not sure what is the problem. Does someone has an idea?

Thanks a lot in advance.

**Comment by jamesjulier** [comment]
I have the same issue

**Comment by stewilliams-extr** [comment]
Are you selecting Thin or Thick on the Disk.  Try using Thick.

**Comment by jamesjulier** [comment]
already set as thick. 

Thick provisioned, lazily zeroed

**Comment by gauthierpjn** [comment]
I have it working now, here are the settings for the Hard Disk: 

Capacity	4 GB
Thin provisioned	No
**Controller	IDE 0:0**
Mode	Dependent

**Comment by stewilliams-extr** [comment]
In my testing I was able to get it to work with the the IDE being set to 0:0.  Thanks for the follow up.  I have added requirements for ESXI in commit#: https://github.com/extremenetworks/Virtual_EXOS/commit/84918ffb3e810e5527307bb832d33a0b99b277b2.
