### ISSUE TITLE
GNS3

### ISSUE THREAD

**Issue by munirsms** [extremenetworks/Virtual_EXOS#4]
how can I setup GNS3 on Macbook?

**Comment by btclay** [comment]
I've been working on a guide for macOS for a little while, and I just finished it up and published it. 

https://github.com/extremenetworks/Virtual_EXOS/blob/master/GNS3_EXOS-VM_Guide_macOS.md

**Comment by munirsms** [comment]
dears,

thank for replay on my message, but still i facing problem with GNS3 when i do set up on my MacBook Apple where it is show my this note when i try open the GNS3,

Error when connecting to the GNS3 server:
cannot connect to http://127.0.0.1:3080.Please check if GNS3 is allow in your antivirus and firewall.and that server version is 2.0.2.



thanks

**Comment by btclay** [comment]
I'd recommend posting this issue on [The Hub](https://community.extremenetworks.com/extreme). It will likely get more attention (as well as attention from people who may better about the intricacies of VMware Fusion networking).
