### ISSUE TITLE
EXOS VM Unstable in VMWare Fusion 10

### ISSUE THREAD

**Issue by lugeha** [extremenetworks/Virtual_EXOS#8]
Running 22.4.1.4 in VMWare fusion, either directly or nested in GNS3, is very unstable. Random processes will crash at random times. At worst it will fail to boot with a kernel panic.
[kernelpanic.txt](https://github.com/extremenetworks/Virtual_EXOS/files/1613390/kernelpanic.txt)

If it does manage to boot, process will crash from time to time
[appcrash.txt](https://github.com/extremenetworks/Virtual_EXOS/files/1613393/appcrash.txt)

This is not a problem in VMWare Fusion 8.

**Comment by stewilliams-extr** [comment]
Does this happen when running a unconfigured switch?  If not, what does your switch configuration look like.

**Comment by lugeha** [comment]
This will happen on an unconfigured switch.

**Comment by lugeha** [comment]
The problem appears to be with the newer hardware versions. Setting the VM to version 12 resolves this issue.

**Comment by stewilliams-extr** [comment]
@lugeha thanks for the update.  I will close this out.
