### ISSUE TITLE
qcow2 for eve-ng

### ISSUE THREAD

**Issue by dvinni** [extremenetworks/Virtual_EXOS#9]
Will you add guide and qcow2 image for eve-ng project?

**Comment by stewilliams-extr** [comment]
I did a quick test and it worked with eve-ng but it took a while to boot.  See if you can get it working with this template below.  Just download the qemu files linked in this repo and place them in the right folder with the correct name.

`root@eve-ng:/opt/unetlab/addons/qemu# ls extremexos-22.4.1.4/
hda.qcow2
`
File located at /opt/unetlab/html/templates/extremexos.php  Make sure you back it up. 
`<?php
$p['type'] = 'qemu';
$p['name'] = 'EXOS'; 
$p['cpulimit'] = 1;
$p['icon'] = 'Switch L3.png'; 
$p['cpu'] = 1;
$p['ram'] = 256; 
$p['ethernet'] = 13; 
$p['console'] = 'telnet'; 
$p['qemu_arch'] = 'i386';
$p['qemu_options'] = '-cpu core2duo -boot order=dc -machine type=pc-1.0 -nographic';
?>
`

**Comment by dvinni** [comment]
Yes, it's working. But if we use EXOS_VM 22.4.1.4 with 16.1.1.4, it see each other with edp command, but ping and routing doesn't work.

**Comment by stewilliams-extr** [comment]
Archive issue as it looks to be a eve-ng issue.
